Repository FatePet/fatepet-fe, pull requests merged in 2025-05, with the labels that each got.

#7 Style: 색상 변수화 작업 및 화면 최소 최대 너비 지정
  src/app/styles/globals.css
  src/app/styles/variables.css
Labels: STYLE, 정재호

#8 Style: 공통 컴포넌트 퍼블리싱 완료(버튼, 모달, 헤더, 입력창, 태그)
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  public/icons/alertIcon.svg
  public/icons/registerIcon.svg
  public/images/backArrow.png
  public/images/mockupImage1.png
  public/images/mockupImage2.png
  public/images/mockupImage3.png
  public/logo/fatepetLogo.svg
  src/app/admin/edit-store/[storeId]/page.tsx
  src/app/admin/login/page.tsx
  src/app/admin/main/page.tsx
  src/app/admin/register-store/page.tsx
  src/app/admin/view-store/[storeId]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/globals.css
  src/app/styles/variables.css
  src/app/user/main/page.tsx
  src/app/user/register-location/page.tsx
  src/app/user/view-store/[storeId]/page.tsx
  src/app/user/view-store/list/page.tsx
  src/components/RQProvider.tsx
  src/components/buttons/BigButton.tsx
  src/components/buttons/CompleteButton.tsx
  src/components/buttons/DeleteButton.tsx
  src/components/buttons/MiniButton.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/RegisterCostButton.tsx
  src/components/buttons/RoundedButton.tsx
  src/components/buttons/StartConsultButton.tsx
  src/components/headers/HeaderWithBackArrow.tsx
  src/components/headers/HeaderWithOnlyText.tsx
  src/components/headers/HeaderWithRightbutton.tsx
  src/components/inputs/LongInput.tsx
  src/components/inputs/TextArea.tsx
  src/components/modals/AlertModal.tsx
  src/components/modals/CancelConfirmModal.tsx
  src/components/modals/ModalLayout.tsx
  src/components/tag/Tag.tsx
  tailwind.config.js
Labels: STYLE, 정재호, 📜 DOCS

#10 style: 관리자 로그인 페이지 구현
  package-lock.json
  package.json
  src/app/admin/login/page.tsx
  src/components/inputs/LongInput.tsx
  src/store/useLoginStore.tsx
  src/types/LoginTypes.d.ts
Labels: STYLE, 장동연

#12 Style: 업체등록 페이지 퍼블리싱
  src/app/admin/edit-business/[storeId]/page.tsx
  src/app/admin/edit-store/[storeId]/page.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/_components/MoreInfoArea.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/app/admin/register-store/page.tsx
  src/app/admin/view-business/[storeId]/page.tsx
  src/app/admin/view-store/[storeId]/page.tsx
  src/app/styles/globals.css
  src/app/styles/reset.css
  src/app/styles/variables.css
  src/components/buttons/MiniButton.tsx
  src/components/headers/HeaderWithBackArrow.tsx
  src/components/inputs/TextArea.tsx
Labels: STYLE, 이수현

#15 Style: 업체 상담 요청 모달 퍼블리싱
  public/icons/checkOffIcon.svg
  public/icons/checkOnIcon.svg
  public/icons/rightArrowIcon.svg
  src/app/page.tsx
  src/app/user/view-business/[businessId]/_components/ConsultModal.tsx
  src/app/user/view-business/[businessId]/page.tsx
  src/app/user/view-business/[category]/list/page.tsx
  src/app/user/view-store/[storeId]/page.tsx
  src/app/user/view-store/list/page.tsx
  src/components/inputs/LongInput.tsx
  src/components/inputs/TextArea.tsx
Labels: STYLE, 정재호, 🛠️ FIX

#19 Feat: 이미지 업로드 기능, 서비스 추가 로직 작성
  src/app/admin/register-business/_components/AdditionalInfoArea.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/_components/ImageUploadButton.tsx
  src/app/admin/register-business/_components/MoreInfoArea.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/types/Admin/Business.d.ts
  src/types/Admin/LoginTypes.d.ts
Labels: 이수현, 🚀 FEAT

#21 Fix: color variables, button&input 컴포넌트 추가, 서비스 삭제 로직
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/app/page.tsx
  src/app/styles/variables.css
  src/components/buttons/MediumButton.tsx
  src/components/buttons/StartConsultButton.tsx
  src/components/inputs/RightButtonInput.tsx
  src/components/tag/Tag.tsx
  tailwind.config.js
Labels: STYLE, 이수현, 🚀 FEAT, 🛠️ FIX

#26 style: 관리자 메인 페이지 퍼블리싱
  src/app/admin/main/_components/AdminBusinessCard.tsx
  src/app/admin/main/_components/adminMockup.ts
  src/app/admin/main/page.tsx
  src/types/Admin/Business.d.ts
Labels: STYLE, 장동연

#32 Feat: 업체등록 페이지 input 필드 형식 검사 및 api 연동 위한 데이터 객체 정의
  src/app/admin/register-business/_components/AdditionalInfoArea.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/types/Admin/Business.d.ts
Labels: 이수현, 🚀 FEAT

#44 Feat: 업체등록 주소검색 & 사용자 위치 설정 기능 구현 + font 적용
  package-lock.json
  package.json
  public/fonts/PretendardVariable.woff2
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/globals.css
  src/components/buttons/MiniButton.tsx
  src/components/location/DaumPost.tsx
  src/components/modals/RegisterLocationModal.tsx
  src/hooks/useConvertAddressToCoordinates.ts
  src/hooks/useGetAddressFromCoords.ts
  src/store/useUserLocationStore.tsx
Labels: STYLE, 이수현, 🚀 FEAT

#47 사용자 메인 - 카테고리 선택 페이지 퍼블리싱
  public/icons/userCategory/accIcon.svg
  public/icons/userCategory/breederIcon.svg
  public/icons/userCategory/counselIcon.svg
  public/icons/userCategory/rainbowIcon.svg
  src/app/admin/main/_components/AdminBusinessCard.tsx
  src/app/admin/main/page.tsx
  src/app/user/main/_components/UserCategory.tsx
  src/app/user/main/_components/categoryStyles.ts
  src/app/user/main/page.tsx
  src/components/user/BusinessCard.tsx
Labels: STYLE, 장동연

#37 Feat: 관리자 로그인 api 연동
  src/_lib/apiRoutes.ts
  src/api/admin/auth/postAdminLogin.ts
  src/app/admin/login/page.tsx
  src/app/user/view-business/[category]/list/page.tsx
  src/components/location/DaumPost.tsx
  src/components/modals/RegisterLocationModal.tsx
  src/store/useAuthStore.tsx
  src/store/useLoginStore.tsx
  src/types/admin/LoginTypes.d.ts
Labels: 정재호, 🚀 FEAT

#40 Feat: 로그인 여부에 따른 관리자 하위 페이지 리디렉션 로직 작성
  README.md
  package.json
  server.js
  setup-https.sh
  src/app/admin/layout.tsx
  src/app/admin/login/page.tsx
  src/app/admin/page.tsx
  src/app/user/main/page.tsx
  src/components/modals/RegisterLocationModal.tsx
  src/store/useAuthStore.tsx
Labels: 정재호, 🚀 FEAT

#51 Feat: /(루트페이지), /user(유저 첫페이지) 경로 잡기
  src/app/page.tsx
  src/app/user/page.tsx
Labels: 정재호, 🚀 FEAT

#53 Feat: 관리자, 사용자 - 업체 상세 정보 조회 api 연동
  next.config.ts
  src/_lib/apiRoutes.ts
  src/api/admin/auth/postAdminLogin.ts
  src/api/admin/business/getAdminBusinessDetail.ts
  src/api/user/business/getUserBusinessDetail.ts
  src/app/admin/login/page.tsx
  src/app/admin/main/_components/AdminBusinessCard.tsx
  src/app/admin/main/_components/adminMockup.ts
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/view-business/[businessId]/page.tsx
  src/app/user/main/page.tsx
  src/app/user/view-business/[category]/[businessId]/_components/AdditionalInfoList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/OptionalServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/PackageServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/PrimaryServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/mockupData.ts
  src/app/user/view-business/[category]/[businessId]/page.tsx
  src/app/user/view-business/[category]/list/_components/SortOptionModal.tsx
  src/app/user/view-business/[category]/list/_components/getUserBusinessListData.ts
  src/app/user/view-business/[category]/list/page.tsx
  src/components/buttons/ModalButton.tsx
  src/components/modals/CancelConfirmModal.tsx
  src/components/modals/RegisterLocationModal.tsx
  src/components/user/BusinessCard.tsx
  src/hooks/api/admin/auth/usePostAdminLogin.ts
  src/hooks/api/admin/business/useGetAdminBusinessDetail.ts
  src/hooks/api/user/useGetUserBusinessDetail.ts
  src/types/Admin/Business.d.ts
  src/types/common/Business.d.ts
  src/types/common/ResponseType.d.ts
  src/types/user/BusinessTypes.d.ts
Labels: 정재호, 🚀 FEAT, 🛠️ FIX

#55 hotfix: EC2로 바뀜에 따른 토큰 갱신 api 호출 로직 수정
  src/_lib/fetcher.ts
Labels: 정재호, 🚨 HOTFIX

#59 관리자 업체 목록 조회 api 연동
  src/_lib/apiRoutes.ts
  src/api/admin/business/getAdminBusiness.ts
  src/app/admin/main/_components/AdminBusinessCard.tsx
  src/app/admin/main/page.tsx
  src/hooks/api/admin/business/useGetAdminBusiness.ts
  src/types/Admin/Business.d.ts
Labels: 장동연, 🚀 FEAT

#61 Fix: CancelConfirmModal 컴포넌트에서 확인, 취소 버튼 위치 뒤바꿈
  src/_lib/apiRoutes.ts
  src/api/admin/business/deleteAdminBusiness.ts
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/view-business/[businessId]/page.tsx
  src/components/modals/CancelConfirmModal.tsx
Labels: STYLE, 정재호, 🛠️ FIX

#67 Feat: 상담 요청 api 연동
  src/_lib/apiRoutes.ts
  src/api/user/business/postRequestConsultation.ts
  src/app/admin/main/_components/adminMockup.ts
  src/app/layout.tsx
  src/app/user/view-business/[category]/[businessId]/_components/ConsultModal.tsx
  src/app/user/view-business/[category]/[businessId]/_components/mockupData.ts
  src/app/user/view-business/[category]/[businessId]/page.tsx
  src/hooks/api/user/business/useGetUserBusinessDetail.ts
  src/hooks/api/user/business/usePostRequestConsultation.ts
  src/types/user/BusinessTypes.d.ts
Labels: 정재호, 🚀 FEAT

#71 Document: CI/CD 자동화 배포를 위한 main.yml 파일 작성
  .github/workflows/main.yml
Labels: DEPLOY, 정재호, 📜 DOCS

#73 fix: main.yml에서 script 수정
  .github/workflows/main.yml
Labels: 정재호, 🛠️ FIX

#69 Feat/#57
  src/api/user/business/getUserBusiness.ts
  src/app/admin/main/page.tsx
  src/app/user/view-business/[category]/list/_components/getUserBusinessListData.ts
  src/app/user/view-business/[category]/list/page.tsx
  src/hooks/api/user/useGetUserBusiness.ts
Labels: 장동연, 🚀 FEAT

#83 Fix: 1차 QA 개선 사항 수정
  src/api/user/business/getUserBusiness.ts
  src/app/loading.tsx
  src/app/user/view-business/[category]/[businessId]/page.tsx
  src/app/user/view-business/[category]/list/_components/SortOptionModal.tsx
  src/app/user/view-business/[category]/list/page.tsx
  src/components/buttons/StartConsultButton.tsx
  src/hooks/api/user/useGetUserBusiness.ts
  tailwind.config.js
Labels: STYLE, 정재호, 🛠️ FIX
