Repository FatePet/fatepet-fe, pull requests merged in 2025-06, with the labels that each got.

#89 Fix:1차 QA 수정사항 반영
  src/app/admin/edit-business/[businessId]/_components/EditBusinessInfoArea.tsx
  src/app/admin/edit-business/[businessId]/page.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/components/inputs/RightButtonInput.tsx
  src/components/inputs/TextArea.tsx
  src/hooks/useCheckDuplicateName.ts
Labels: ♻️ REFACTOR, STYLE, 이수현, 🛠️ FIX

#86 Fix: 관리자 업체 조회 페이지 QA 반영
  src/app/admin/main/_components/AdminBusinessCard.tsx
  src/app/admin/main/page.tsx
  src/app/styles/globals.css
  src/app/user/view-business/[category]/list/page.tsx
Labels: STYLE, 장동연, 🛠️ FIX

#93 Fix: 2차 QA 개선사항 수정
  src/app/admin/edit-business/[businessId]/_components/EditBusinessInfoArea.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/user/main/page.tsx
  src/app/user/view-business/[category]/[businessId]/_components/OptionalServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/PackageServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/PrimaryServiceList.tsx
  src/app/user/view-business/[category]/list/page.tsx
  src/components/location/DaumPost.tsx
  src/components/location/LocationBar.tsx
  src/components/modals/RegisterLocationModal.tsx
  src/hooks/api/user/business/useGetUserBusiness.ts
  src/store/useUserLocationStore.tsx
Labels: 정재호, 🐛 BUG, 🛠️ FIX

#95 Fix: 2차 QA 업체 등록 & 수정
  src/app/admin/edit-business/[businessId]/_components/EditBusinessInfoArea.tsx
  src/app/admin/edit-business/[businessId]/page.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/components/buttons/MediumButton.tsx
  src/components/inputs/RightButtonInput.tsx
Labels: 이수현, 🛠️ FIX

#96 Deploy: 2차 qa 개선 사항 수정
  src/app/admin/edit-business/[businessId]/_components/EditBusinessInfoArea.tsx
  src/app/admin/edit-business/[businessId]/page.tsx
  src/app/admin/register-business/_components/BusinessInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/app/user/main/page.tsx
  src/app/user/view-business/[category]/[businessId]/_components/OptionalServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/PackageServiceList.tsx
  src/app/user/view-business/[category]/[businessId]/_components/PrimaryServiceList.tsx
  src/app/user/view-business/[category]/list/page.tsx
  src/components/buttons/MediumButton.tsx
  src/components/inputs/RightButtonInput.tsx
  src/components/location/DaumPost.tsx
  src/components/location/LocationBar.tsx
  src/components/modals/RegisterLocationModal.tsx
  src/hooks/api/user/business/useGetUserBusiness.ts
  src/store/useUserLocationStore.tsx
Labels: 정재호, 이수현, 🐛 BUG, 🛠️ FIX

#98 bug: 위치 설정 되있는 상태에 거리순 정렬일때 위치가 초기화되면 빈페이지에 에러나는 문제 수정
  src/app/user/view-business/[category]/list/page.tsx
Labels: 정재호, 🐛 BUG, 🚨 HOTFIX

#101 fix: 위치설정 완료 눌렀을 때만 로컬스토리지 저장
  src/components/location/DaumPost.tsx
  src/components/modals/RegisterLocationModal.tsx
Labels: 이수현, 🛠️ FIX

#102 deploy:
  src/app/user/view-business/[category]/list/page.tsx
  src/components/location/DaumPost.tsx
  src/components/modals/RegisterLocationModal.tsx
Labels: 정재호, 이수현, 🐛 BUG, 🚨 HOTFIX

#105 Refactor & Fix: 업체 등록/수정 서비스 관련 코드 리팩토링
  src/app/admin/edit-business/[businessId]/_components/EditServiceCard.tsx
  src/app/admin/edit-business/[businessId]/_components/EditServiceInfoArea.tsx
  src/app/admin/edit-business/[businessId]/page.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/hooks/admin-business/useServiceInputChange.ts
Labels: ♻️ REFACTOR, 이수현, 🛠️ FIX

#106 Deploy: 서비스 관련 로직 수정
  src/app/admin/edit-business/[businessId]/_components/EditServiceCard.tsx
  src/app/admin/edit-business/[businessId]/_components/EditServiceInfoArea.tsx
  src/app/admin/edit-business/[businessId]/page.tsx
  src/app/admin/register-business/_components/ServiceCard.tsx
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
  src/app/admin/register-business/page.tsx
  src/hooks/admin-business/useServiceInputChange.ts
Labels: DEPLOY, ♻️ REFACTOR, 이수현, 🛠️ FIX

#109 fix: 서비스 추가시 기본값 설정
  src/app/admin/register-business/_components/ServiceInfoArea.tsx
Labels: 이수현, 🐛 BUG, 🚨 HOTFIX
